apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

images:
- name: kreajith2026/argocd
  newName: kreajith2026/argocd
  newTag: "31"
- name: kreajith2026/argocd-1
  newName: kreajith2026/argocd-1
  newTag: "9"
