apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

images:
  - name: kreajith2026/argocd
    newTag: "28"
  - name: kreajith2026/argocd-1
    newTag: "2"
