apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: trip-deployment-sit
  target:
    kind: Deployment
    name: trip-deployment-sit
- patch: |
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: vts-deployment-sit
  target:
    kind: Deployment
    name: vts-deployment-sit

images:
- name: kreajith2026/trip-sit
  newName: kreajith2026/trip-sit
  newTag: "39"
- name: kreajith2026/vts-sit
  newName: kreajith2026/vts-sit
  newTag: "16"
