apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: trip-deployment-main
  target:
    kind: Deployment
    name: trip-deployment-main
- patch: |
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: vts-deployment-main
  target:
    kind: Deployment
    name: vts-deployment-main

images:
- name: kreajith2026/trip-main
  newName: kreajith2026/trip-main
  newTag: "37"
- name: kreajith2026/vts-main
  newName: kreajith2026/vts-main
  newTag: "15"
